export const AVAILABLE_CLASSES = ['1', '2', '3', '4', '5', '6', '7', '8', '9', '10', '11', '12'];
export const SECTIONS = ['A', 'B', 'C', 'D', 'E', 'F'];

export const MOCK_TEACHERS = [
  // School 1 Teachers
  {
    id: 1,
    fullName: 'Mr. Robert Chen',
    email: 'robert.chen@school.edu',
    phone: '+91 9876543003',
    designation: 'Senior Mathematics Teacher',
    subjects: ['Mathematics', 'Calculus'],
    sections: [
      { class: '4', sections: ['A', 'B'] },
      { class: '5', sections: ['A', 'C'] },
      { class: '6', sections: ['B'] },
    ],
    joinDate: '2020-07-05',
    address: '78 Green Street, Knowledge City',
    education: 'M.Sc. in Mathematics',
    experience: '8 years',
    profileImage: 'https://randomuser.me/api/portraits/men/64.jpg',
    isClassIncharge: true,
    inchargeClass: '4',
    inchargeSection: 'A',
    status: 'active',
    schoolId: 1,
    username: 'robert.chen'
  },
  {
    id: 2,
    fullName: 'Ms. Jennifer Davis',
    email: 'jennifer.davis@school.edu',
    phone: '+91 9876543004',
    designation: 'Science Teacher',
    subjects: ['Biology', 'Environmental Science'],
    sections: [
      { class: '7', sections: ['A', 'B', 'C'] },
      { class: '8', sections: ['A', 'B'] },
    ],
    joinDate: '2019-08-15',
    address: '42 Oak Avenue, Knowledge City',
    education: 'Ph.D. in Biology',
    experience: '6 years',
    profileImage: 'https://randomuser.me/api/portraits/women/35.jpg',
    isClassIncharge: true,
    inchargeClass: '7',
    inchargeSection: 'B',
    status: 'active',
    schoolId: 1,
    username: 'jennifer.davis'
  },
  {
    id: 3,
    fullName: 'Mr. Sanjay Kumar',
    email: 'sanjay.kumar@school.edu',
    phone: '+91 9876543005',
    designation: 'History Teacher',
    subjects: ['History', 'Social Studies'],
    sections: [
      { class: '9', sections: ['A', 'B'] },
      { class: '10', sections: ['A', 'C'] },
    ],
    joinDate: '2018-06-20',
    address: '15 River Road, Knowledge City',
    education: 'M.A. in History',
    experience: '10 years',
    profileImage: 'https://randomuser.me/api/portraits/men/32.jpg',
    isClassIncharge: false,
    inchargeClass: '',
    inchargeSection: '',
    status: 'active',
    schoolId: 1,
    username: 'sanjay.kumar'
  },
  {
    id: 4,
    fullName: 'Mrs. Priya Sharma',
    email: 'priya.sharma@school.edu',
    phone: '+91 9876543006',
    designation: 'English Teacher',
    subjects: ['English Literature', 'Grammar'],
    sections: [
      { class: '11', sections: ['A', 'B'] },
      { class: '12', sections: ['A'] },
    ],
    joinDate: '2017-07-10',
    address: '89 Mountain View, Knowledge City',
    education: 'M.A. in English Literature',
    experience: '12 years',
    profileImage: 'https://randomuser.me/api/portraits/women/67.jpg',
    isClassIncharge: true,
    inchargeClass: '11',
    inchargeSection: 'A',
    status: 'active',
    schoolId: 1,
    username: 'priya.sharma'
  },
  {
    id: 5,
    fullName: 'Mr. David Wilson',
    email: 'david.wilson@school.edu',
    phone: '+91 9876543007',
    designation: 'Physics Teacher',
    subjects: ['Physics', 'Mathematics'],
    sections: [
      { class: '9', sections: ['A', 'B', 'C'] },
      { class: '10', sections: ['A', 'B'] },
    ],
    joinDate: '2019-06-15',
    address: '23 Sunshine Boulevard, Knowledge City',
    education: 'M.Sc. in Physics',
    experience: '7 years',
    profileImage: 'https://randomuser.me/api/portraits/men/22.jpg',
    isClassIncharge: false,
    inchargeClass: '',
    inchargeSection: '',
    status: 'active',
    schoolId: 1,
    username: 'david.wilson'
  },
  
  // School 2 Teachers
  {
    id: 6,
    fullName: 'Ms. Sarah Johnson',
    email: 'sarah.johnson@school.edu',
    phone: '+91 9876543008',
    designation: 'Chemistry Teacher',
    subjects: ['Chemistry', 'Environmental Science'],
    sections: [
      { class: '9', sections: ['A', 'B'] },
      { class: '10', sections: ['A', 'B', 'C'] },
    ],
    joinDate: '2018-08-20',
    address: '56 Lake View, Harmony Town',
    education: 'M.Sc. in Chemistry',
    experience: '9 years',
    profileImage: 'https://randomuser.me/api/portraits/women/28.jpg',
    isClassIncharge: true,
    inchargeClass: '10',
    inchargeSection: 'B',
    status: 'active',
    schoolId: 2,
    username: 'sarah.johnson'
  },
  {
    id: 7,
    fullName: 'Mr. Michael Brown',
    email: 'michael.brown@school.edu',
    phone: '+91 9876543009',
    designation: 'Computer Science Teacher',
    subjects: ['Computer Science', 'Mathematics'],
    sections: [
      { class: '11', sections: ['A', 'B'] },
      { class: '12', sections: ['A', 'B'] },
    ],
    joinDate: '2019-07-25',
    address: '34 Tech Street, Harmony Town',
    education: 'M.Tech in Computer Science',
    experience: '5 years',
    profileImage: 'https://randomuser.me/api/portraits/men/76.jpg',
    isClassIncharge: true,
    inchargeClass: '12',
    inchargeSection: 'A',
    status: 'active',
    schoolId: 2,
    username: 'michael.brown'
  },
  {
    id: 8,
    fullName: 'Ms. Ananya Patel',
    email: 'ananya.patel@school.edu',
    phone: '+91 9876543010',
    designation: 'Arts Teacher',
    subjects: ['Fine Arts', 'Craft'],
    sections: [
      { class: '6', sections: ['A', 'B', 'C'] },
      { class: '7', sections: ['A', 'B'] },
      { class: '8', sections: ['A', 'B'] },
    ],
    joinDate: '2020-06-10',
    address: '67 Creative Lane, Harmony Town',
    education: 'BFA in Fine Arts',
    experience: '4 years',
    profileImage: 'https://randomuser.me/api/portraits/women/45.jpg',
    isClassIncharge: false,
    inchargeClass: '',
    inchargeSection: '',
    status: 'active',
    schoolId: 2,
    username: 'ananya.patel'
  },
  
  // School 3 Teachers
  {
    id: 9,
    fullName: 'Mr. James Wilson',
    email: 'james.wilson@school.edu',
    phone: '+91 9876543011',
    designation: 'Physical Education Teacher',
    subjects: ['Physical Education', 'Health'],
    sections: [
      { class: '1', sections: ['A', 'B'] },
      { class: '2', sections: ['A', 'B'] },
      { class: '3', sections: ['A', 'B'] },
    ],
    joinDate: '2017-08-05',
    address: '12 Sports Avenue, Greenfield',
    education: 'B.Ed in Physical Education',
    experience: '11 years',
    profileImage: 'https://randomuser.me/api/portraits/men/52.jpg',
    isClassIncharge: true,
    inchargeClass: '3',
    inchargeSection: 'A',
    status: 'active',
    schoolId: 3,
    username: 'james.wilson'
  },
  {
    id: 10,
    fullName: 'Ms. Emily Rodriguez',
    email: 'emily.rodriguez@school.edu',
    phone: '+91 9876543012',
    designation: 'Music Teacher',
    subjects: ['Music', 'Vocal Training'],
    sections: [
      { class: '4', sections: ['A', 'B'] },
      { class: '5', sections: ['A', 'B'] },
    ],
    joinDate: '2019-07-15',
    address: '45 Melody Street, Greenfield',
    education: 'B.A. in Music',
    experience: '6 years',
    profileImage: 'https://randomuser.me/api/portraits/women/75.jpg',
    isClassIncharge: false,
    inchargeClass: '',
    inchargeSection: '',
    status: 'active',
    schoolId: 3,
    username: 'emily.rodriguez'
  },
  {
    id: 11,
    fullName: 'Mr. Rajesh Gupta',
    email: 'rajesh.gupta@school.edu',
    phone: '+91 9876543013',
    designation: 'Economics Teacher',
    subjects: ['Economics', 'Business Studies'],
    sections: [
      { class: '11', sections: ['A', 'B'] },
      { class: '12', sections: ['A', 'B'] },
    ],
    joinDate: '2016-06-20',
    address: '78 Commerce Road, Greenfield',
    education: 'M.Com in Economics',
    experience: '12 years',
    profileImage: 'https://randomuser.me/api/portraits/men/41.jpg',
    isClassIncharge: true,
    inchargeClass: '12',
    inchargeSection: 'B',
    status: 'active',
    schoolId: 3,
    username: 'rajesh.gupta'
  }
];